name: Destroy-EKS-Grafana-Dashboards

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Destroy
        run: terraform plan -destroy -out=tfplan-destroy

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve tfplan-destroy
